#!/bin/bash
#PBS -N Floyds-Parallel64CPU
#PBS -l select=4:ncpus=16:mpiprocs=64:mem=4gb
#PBS -l walltime=00:30:00
#PBS -j oe

source /etc/profile.d/modules.sh
module purge
module add gcc/4.8.1 openmpi/1.8.4

cd $PBS_O_WORKDIR

mpiexec -n 64 ./floyd-parallel Graph1000.dat Graph1000Out64P.dat

mpiexec -n 64 ./floyd-parallel Graph2000.dat Graph2000Out64P.dat

mpiexec -n 64 ./floyd-parallel Graph3000.dat Graph3000Out64P.dat

